### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by popokatapepel**
since I had quite a struggle with mapping your paper to the source code im seeing I created a html-doc for the package from your docstring using sphinx-autoapi. maybe thats useful for other users

simply do:

    $ cd docs
    $ make html

the html referencs is in `docs/build` afterwards

### CODE REVIEW

**Comment by cgnorthcutt** [comment]
Hi @popokatapepel ,  Great suggestion. I've merged. But let's take it a step further and host the docs on readthedocs.org.

Would you like to take a stab at modifying the current set-up to integrate automatically with readthedocs?

**Comment by popokatapepel** [comment]
sure. although i never uploaded any docs i think i will figure it out

**Comment by popokatapepel** [comment]
ok i just tried it and that is pretty straight forward. However, the documentation already exists at https://cleanlab.readthedocs.io/en/latest/ so you probably already solved it your self.

**Comment by cgnorthcutt** [comment]
Hi @popokatapepel , indeed, I added a hook to readthedocs, but I'm wondering if you would be willing to help witt the formatting? For example, https://pip.readthedocs.io/ looks nice. Even some simple changes such as adding spacing between the function declarations/docs and some light color (to lightly match the logo).

**Pull request merged**
